theme: jekyll-theme-hacker
title: "Keloran blog and random stuff"
url: "https://www.keloran.dev"

analytics:
  provider: "google-universal"
  google:
    tracking_id: UA-4194218-11

atom_feed:
  path:

plugins:
  - jekyll-feed
